### ISSUE TITLE
Missing exception handling

### ISSUE THREAD

**Issue by kelvin-dev** [stevdza-san/OneTapCompose#32]
Missing exception handling at the else clause, line 108, [Missing exception handling](https://github.com/stevdza-san/OneTapCompose/blob/1e38adfe9a2e3e47d3fd1e46d5fd1d5be498f991/onetap/src/main/java/com/stevdzasan/onetap/OneTapCompose.kt)

![image](https://github.com/user-attachments/assets/bc046794-4eb3-41db-a035-f1ea1ef30ec3)

```During begin sign in, failure response from one tap: 8: [8] UNKNOWN EXCEPTION - java.lang.IllegalArgumentException: ProtoDataStoreConfig<wli> doesn't match previous call [uri=android://com.google.android.gms/files/auth_api_credentials/com.google%3Ameow.test2000%40gmail.com/gislamssettings.pb] [variantConfig]
```
Thanks

**Comment by stevdza-san** [comment]
Thanks for your feedback! I'll take a look and update the library tomorrow hopefully!

**Comment by kelvin-dev** [comment]
> Thanks for your feedback! I'll take a look and update the library tomorrow hopefully!

we love your work, for further investigation, please fix below issue on your lib my dear, we already recorded the fatal log, 
```During begin sign in, failure response from one tap: 8: [8] UNKNOWN EXCEPTION - java.lang.IllegalArgumentException: ProtoDataStoreConfig<wli> doesn't match previous call [uri=android://com.google.android.gms/files/auth_api_credentials/com.google%3Ameow.test404%40gmail.com/gislamssettings.pb] [variantConfig]```
that happens on new APK fresh install,
Tons of thanks

**Comment by stevdza-san** [comment]
I've just pushed a new release, v1.0.13.

**Comment by kelvin-dev** [comment]
> > Thanks for your feedback! I'll take a look and update the library tomorrow hopefully!
> 
> we love your work, for further investigation, please fix below issue on your lib my dear, we already recorded the fatal log, `During begin sign in, failure response from one tap: 8: [8] UNKNOWN EXCEPTION - java.lang.IllegalArgumentException: ProtoDataStoreConfig<wli> doesn't match previous call [uri=android://com.google.android.gms/files/auth_api_credentials/com.google%3Ameow.test404%40gmail.com/gislamssettings.pb] [variantConfig]` that happens on new APK fresh install, Tons of thanks

we pull your latest source , that issue stills persist on your high level implementation

**Comment by stevdza-san** [comment]
@kelvin-dev I'm not sure that the error is associated with this library. It seems you have an issue with the proto data store?

**Comment by kelvin-dev** [comment]
> @kelvin-dev I'm not sure that the error is associated with this library. It seems you have an issue with the proto data store?

proto data store ? we dont use any library in our dependencies, we been evaluating on fresh installs, say , Android 7, API 25, would you please have a unit test on Bluestack VMs,

**Comment by kelvin-dev** [comment]
fyi, we dont use any lib on  proto datastore

![image](https://github.com/user-attachments/assets/d0521980-aef4-4792-9868-1f50f410480f)

![image](https://github.com/user-attachments/assets/d7ffd2f1-4cac-48d4-84e7-3d2d8142a9aa)

**Comment by stevdza-san** [comment]
@kelvin-dev I've fixed one exception handling issue in the new v1.0.13. Try updating the library and check it out?

**Comment by kelvin-dev** [comment]
weve been on your version v1.0.13 so far, please fix the root cause, your lib keep throwing at that exception
